In [1]:
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

import numpy as np
import torch

import helper


In [2]:
x = torch.rand(3,2)
x

tensor([[0.7211, 0.0318],
        [0.4140, 0.1799],
        [0.1738, 0.3464]])

In [5]:
y = torch.ones(x.size())
y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [6]:
z = x + y
z

tensor([[1.7211, 1.0318],
        [1.4140, 1.1799],
        [1.1738, 1.3464]])

In [7]:
z[0]

tensor([1.7211, 1.0318])

In [8]:
z[:, 1:]

tensor([[1.0318],
        [1.1799],
        [1.3464]])

In [9]:
z.add(1)

tensor([[2.7211, 2.0318],
        [2.4140, 2.1799],
        [2.1738, 2.3464]])

In [10]:
z

tensor([[1.7211, 1.0318],
        [1.4140, 1.1799],
        [1.1738, 1.3464]])

In [11]:
z.add_(1)

tensor([[2.7211, 2.0318],
        [2.4140, 2.1799],
        [2.1738, 2.3464]])

In [12]:
z

tensor([[2.7211, 2.0318],
        [2.4140, 2.1799],
        [2.1738, 2.3464]])

In [13]:
#Reshape

z.size()

torch.Size([3, 2])

In [14]:
z.resize(2,3)

/opt/anaconda3/lib/python3.7/site-packages/torch/tensor.py:365: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


tensor([[2.7211, 2.0318, 2.4140],
        [2.1799, 2.1738, 2.3464]])

In [15]:
z

tensor([[2.7211, 2.0318],
        [2.4140, 2.1799],
        [2.1738, 2.3464]])

In [16]:
z.resize_(2,3)

tensor([[2.7211, 2.0318, 2.4140],
        [2.1799, 2.1738, 2.3464]])

In [17]:
z

tensor([[2.7211, 2.0318, 2.4140],
        [2.1799, 2.1738, 2.3464]])

In [18]:
#numpy to torch and back

a = np.random.rand(2,3)
a

array([[0.90647065, 0.88715276, 0.06220807],
       [0.9388334 , 0.86080071, 0.75054688]])

In [19]:
b = torch.from_numpy(a)
b

tensor([[0.9065, 0.8872, 0.0622],
        [0.9388, 0.8608, 0.7505]], dtype=torch.float64)

In [20]:
b.numpy()

array([[0.90647065, 0.88715276, 0.06220807],
       [0.9388334 , 0.86080071, 0.75054688]])

In [21]:
# Multiply PyTorch Tensor by 2, in place

b.mul_(2)

tensor([[1.8129, 1.7743, 0.1244],
        [1.8777, 1.7216, 1.5011]], dtype=torch.float64)

In [22]:
# Numpy array matches new values from Tensor
a

array([[1.8129413 , 1.77430552, 0.12441614],
       [1.8776668 , 1.72160142, 1.50109376]])